spring:
  redis:
    database: 0 # redis 数据库索引默认16个（默认为0）
    host: 127.0.0.1 # ip地址
    password:  # redis 服务器连接密码（默认为空）
    port: 6379
    timeout: 12000  # 连接超时时间（毫秒），默认2000ms
    # cluster:
    # nodes: xxx:7000,xxx:7001,xxx:7002
    # maxRedirects: 6
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  cache:
    redis:
      # 过期时间（毫秒）。默认情况下，永不过期。
      time-to-live: 1d
      # 写入redis时是否使用键前缀。
      use-key-prefix: true
  application:
    name: redis-demo-server

server:
  port: 8095
